package io.github.shrishaanth.axon.diff;

import java.util.Locale;

/** The kinds of atomic change the diff reports. Wire names match the report schema. */
public enum ChangeKind {
    OPERATION_REMOVED,
    OPERATION_ADDED,
    REQUEST_FIELD_REMOVED,
    REQUEST_FIELD_ADDED_OPTIONAL,
    REQUEST_FIELD_ADDED_REQUIRED,
    REQUEST_FIELD_MADE_REQUIRED,
    REQUEST_FIELD_MADE_OPTIONAL,
    REQUEST_FIELD_TYPE_CHANGED,
    REQUEST_ENUM_NARROWED,
    REQUEST_ENUM_WIDENED,
    REQUEST_BODY_ADDED,
    REQUEST_BODY_REMOVED,
    REQUEST_BODY_MADE_REQUIRED,
    REQUEST_BODY_MADE_OPTIONAL,
    RESPONSE_FIELD_REMOVED,
    RESPONSE_FIELD_ADDED,
    RESPONSE_FIELD_MADE_OPTIONAL,
    RESPONSE_FIELD_MADE_REQUIRED,
    RESPONSE_FIELD_TYPE_CHANGED,
    RESPONSE_ENUM_WIDENED,
    RESPONSE_ENUM_NARROWED,
    RESPONSE_STATUS_REMOVED,
    RESPONSE_STATUS_ADDED,
    MEDIA_TYPE_REMOVED,
    MEDIA_TYPE_ADDED;

    public String wire() {
        return name().toLowerCase(Locale.ROOT);
    }
}
